<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CShells.DynamicFeatureFixture</AssemblyName>
    <RootNamespace>CShells.DynamicFeatureFixture</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CShells.AspNetCore.Abstractions\CShells.AspNetCore.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
